#############################################################################
# Makefile for building: final.app/Contents/MacOS/final
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  final.pro
# Template: app
# Command: /Users/sclinck/Qt/5.3/clang_64/bin/qmake -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 -o Makefile final.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
CXX           = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt/5.3/clang_64/mkspecs/macx-g++ -I. -Iglm -Ilib -I/course/cs123/lib/glew/glew-1.10.0/include -I../../../Qt/5.3/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/sclinck/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/sclinck/Qt/5.3/clang_64/lib -L/course/cs123/lib/glew/glew-1.10.0/include -lGLEW -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/sclinck/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		view.cpp \
		lib/ResourceLoader.cpp \
		Databinding.cpp \
		Settings.cpp moc_mainwindow.cpp \
		moc_view.cpp \
		moc_Databinding.cpp
OBJECTS       = main.o \
		mainwindow.o \
		view.o \
		ResourceLoader.o \
		Databinding.o \
		Settings.o \
		moc_mainwindow.o \
		moc_view.o \
		moc_Databinding.o
DIST          = ../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/g++-macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/macx-g++/qmake.conf \
		../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		final.pro main.cpp \
		mainwindow.cpp \
		view.cpp \
		lib/ResourceLoader.cpp \
		Databinding.cpp \
		Settings.cpp
QMAKE_TARGET  = final
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = final.app/Contents/MacOS/final

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile final.app/Contents/PkgInfo final.app/Contents/Resources/empty.lproj final.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d final.app/Contents/MacOS/ || mkdir -p final.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: final.pro ../../../Qt/5.3/clang_64/mkspecs/macx-g++/qmake.conf ../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/g++-macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/macx-g++/qmake.conf \
		../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		final.pro \
		/Users/sclinck/Qt/5.3/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/sclinck/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/sclinck/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/sclinck/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 -o Makefile final.pro
../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt/5.3/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.3/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.3/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.3/clang_64/mkspecs/common/g++-base.conf:
../../../Qt/5.3/clang_64/mkspecs/common/g++-macx.conf:
../../../Qt/5.3/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.3/clang_64/mkspecs/macx-g++/qmake.conf:
../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.3/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.3/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.3/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.3/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.3/clang_64/mkspecs/features/lex.prf:
final.pro:
/Users/sclinck/Qt/5.3/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/sclinck/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/sclinck/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/sclinck/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 -o Makefile final.pro

qmake_all: FORCE

final.app/Contents/PkgInfo: 
	@test -d final.app/Contents || mkdir -p final.app/Contents
	@$(DEL_FILE) final.app/Contents/PkgInfo
	@echo "APPL????" >final.app/Contents/PkgInfo
final.app/Contents/Resources/empty.lproj: 
	@test -d final.app/Contents/Resources || mkdir -p final.app/Contents/Resources
	@touch final.app/Contents/Resources/empty.lproj
	
final.app/Contents/Info.plist: 
	@test -d final.app/Contents || mkdir -p final.app/Contents
	@$(DEL_FILE) final.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,Open.final,g" -e "s,@EXECUTABLE@,final,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.3/clang_64/mkspecs/macx-g++/Info.plist.app >final.app/Contents/Info.plist
dist: 
	@test -d .tmp/final1.0.0 || mkdir -p .tmp/final1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/final1.0.0/ && $(COPY_FILE) --parents mainwindow.h view.h lib/ResourceLoader.h Databinding.h Settings.h lib/CS123Common.h .tmp/final1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp view.cpp lib/ResourceLoader.cpp Databinding.cpp Settings.cpp .tmp/final1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/final1.0.0/ && (cd `dirname .tmp/final1.0.0` && $(TAR) final1.0.0.tar final1.0.0 && $(COMPRESS) final1.0.0.tar) && $(MOVE) `dirname .tmp/final1.0.0`/final1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/final1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r final.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp moc_Databinding.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp moc_Databinding.cpp
moc_mainwindow.cpp: ../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QButtonGroup \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		mainwindow.h
	/Users/sclinck/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/sclinck/Qt/5.3/clang_64/mkspecs/macx-g++ -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer/glm -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer/lib -I/course/cs123/lib/glew/glew-1.10.0/include -I/Users/sclinck/Qt/5.3/clang_64/lib/QtOpenGL.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/sclinck/Qt/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: ../../../Qt/5.3/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		view.h
	/Users/sclinck/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/sclinck/Qt/5.3/clang_64/mkspecs/macx-g++ -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer/glm -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer/lib -I/course/cs123/lib/glew/glew-1.10.0/include -I/Users/sclinck/Qt/5.3/clang_64/lib/QtOpenGL.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/sclinck/Qt/5.3/clang_64/lib view.h -o moc_view.cpp

moc_Databinding.cpp: lib/CS123Common.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/string_cast.hpp \
		glm/gtx/integer.hpp \
		glm/gtx/integer.inl \
		glm/gtx/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.hpp \
		glm/gtx/quaternion.inl \
		glm/gtx/norm.hpp \
		glm/gtx/norm.inl \
		glm/gtx/string_cast.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QCheckBox \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QButtonGroup \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QRadioButton \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTabWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDial \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		Databinding.h
	/Users/sclinck/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/sclinck/Qt/5.3/clang_64/mkspecs/macx-g++ -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer/glm -I/Users/sclinck/Documents/CSCI1230:1234/GPURaytracer/lib -I/course/cs123/lib/glew/glew-1.10.0/include -I/Users/sclinck/Qt/5.3/clang_64/lib/QtOpenGL.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/sclinck/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/sclinck/Qt/5.3/clang_64/lib Databinding.h -o moc_Databinding.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		view.h \
		../../../Qt/5.3/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h
	/Users/sclinck/Qt/5.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		mainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QButtonGroup \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp Databinding.h \
		lib/CS123Common.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/string_cast.hpp \
		glm/gtx/integer.hpp \
		glm/gtx/integer.inl \
		glm/gtx/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.hpp \
		glm/gtx/quaternion.inl \
		glm/gtx/norm.hpp \
		glm/gtx/norm.inl \
		glm/gtx/string_cast.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QCheckBox \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QButtonGroup \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QRadioButton \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTabWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDial \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		mainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_mainwindow.h \
		view.h \
		../../../Qt/5.3/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

view.o: view.cpp lib/ResourceLoader.h \
		view.h \
		../../../Qt/5.3/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o view.cpp

ResourceLoader.o: lib/ResourceLoader.cpp lib/ResourceLoader.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ResourceLoader.o lib/ResourceLoader.cpp

Databinding.o: Databinding.cpp Databinding.h \
		lib/CS123Common.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/string_cast.hpp \
		glm/gtx/integer.hpp \
		glm/gtx/integer.inl \
		glm/gtx/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.hpp \
		glm/gtx/quaternion.inl \
		glm/gtx/norm.hpp \
		glm/gtx/norm.inl \
		glm/gtx/string_cast.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QCheckBox \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QButtonGroup \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QRadioButton \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTabWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDial \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Databinding.o Databinding.cpp

Settings.o: Settings.cpp Settings.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings.o Settings.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_Databinding.o: moc_Databinding.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Databinding.o moc_Databinding.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

